Form content
karmarama/Networking pull request #2
Opened 2019-07-22 10:12 UTC by swwol

2019-07-23 08:52 UTC, timsearle requested changes
Looks great! Glad we got the encoding working. Please improve the test coverage so it hasn't drop so much and there are a few comments/questions throughout.

2019-07-23 08:52 UTC, timsearle commented on Sources/Webservice/HTTP/Headers/ContentType.swift
> +public enum CharSet {
Does this make sense as a top-level type? Seems pretty linked to the JSON content-type? Could nest

2019-07-23 08:52 UTC, timsearle commented on Sources/Webservice/HTTP/Headers/ContentType.swift
> +            return "\"UTF-8\""
How come these are all in escaped quotes?

2019-07-23 08:52 UTC, timsearle commented on Sources/Webservice/HTTP/Headers/ContentType.swift
> +    public init( charSet: CharSet? = nil ) {
Strange spacing

2019-07-23 08:52 UTC, timsearle commented on Sources/Resource/FormEncoder.swift
> +        let plussesReplaced = self.replacingOccurrences(of: "+", with: "%2B")
Why not use the Foundation framework methods to handle percent encoding/decoding? Or use URLComponents?

2019-07-23 08:52 UTC, timsearle commented on Sources/Resource/FormEncoder.swift
> +     let putBackSpaces = self.replacingOccurrences(of: "+", with: " ")
Inconsistent spacing here

2019-07-23 08:52 UTC, timsearle commented on Sources/Resource/FormEncoder.swift
> +        let key = keys[0].appending(bracketedKeys)
This subscript looks unsafe

2019-07-23 08:52 UTC, timsearle commented on Sources/Resource/FormEncoder.swift
> +private struct FormSingleValueEncoding: SingleValueEncodingContainer {
Any chance these could be split into different files seeing as they don't offer any value currently? Also would reduce the line length of FormEncoder.swift

2019-07-23 08:52 UTC, timsearle commented on NetworkingTests/Webservice/FormEncoderTests.swift
> +            print("test passed")
There is an XCTAssertThrows, should be using that if validating errors are thrown

2019-07-23 08:52 UTC, timsearle commented on NetworkingTests/Webservice/FormEncoderTests.swift
> +            print("test passed")
XCTAssertThrows

2019-07-23 09:57 UTC, swwol commented on Sources/Resource/FormEncoder.swift
> +        let plussesReplaced = self.replacingOccurrences(of: "+", with: "%2B")
I am using the addingPercentEncoding method at the end, but first replacing spaces with plusses, ss that is how they are represented in form data, rather that as %20.
Also + and & are excluded from the .urlQueryAllowed characterset, so I am manually encoding them. (After first swapping spaces for +s)

2019-07-23 10:06 UTC, swwol commented on Sources/Webservice/HTTP/Headers/ContentType.swift
> +            return "\"UTF-8\""
thats how it is defined here..
https://www.w3schools.com/tags/att_meta_charset.asp

2019-07-23 15:24 UTC, timsearle commented on Sources/Resource/FormEncoder/FormData.swift
> +//// Created by Nice Agency
Could you delete all of these comment headers from each file?

2019-07-24 09:50 UTC, timsearle commented
Some project structure and naming comments now that I've figured out how to clone down the PR from GitHub:

Rename FormContentType -> FormURLEncodedContentType (this could also be moved under the Webservice > HTTP  > Headers group.

Rename FormEncoder -> FormURLEncoder, including the group name

String+Extension.swift can be moved to where the other extensions live. The name should be formURLEncoded().

Basically instead of Form it should be FormURL everywhere to be explicit as to what these types do.

The FormEncoderTests.swift seem to be in the Webservice group on the test target, this doesn't align with where they are in the code structure. They should be under resource and perhaps create a new group. Also can be renamed appropriately.

2019-07-24 09:51 UTC, timsearle commented on NetworkingTests/Webservice/FormEncoderTests.swift
> +            print (formString)
Can remove all `print()` calls.

2019-07-24 09:52 UTC, timsearle commented on NetworkingTests/Webservice/FormEncoderTests.swift
> +            //swiftlint:disable line_length
This will disable line_length for the whole file. You could put the test string into a multi-line string literal

2019-07-24 09:53 UTC, timsearle commented on NetworkingTests/Webservice/FormEncoderTests.swift
> +            print("Encoding failed: \(error)")
Rather than do, try, catch. You can make the test function `throws`, and XCTest will catch the error and treat it as a test failure

2019-07-25 10:11 UTC, timsearle approved these changes

2019-07-25 10:12 UTC, merged